In [1]:
!pip install pandas
!pip install numpy
!pip install sqlalchemy
!pip install pymysql

Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: numpy>=1.20.3 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (1.24.4)
Requirement already satisfied: sqlalchemy in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (2.0.51)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: greenlet>=1 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: pymysql in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (1.1.2)

In [2]:
import pandas as pd
import numpy as np

print("Pandas Version:", pd.__version__)
print("NumPy Version:", np.__version__)

Pandas Version: 2.3.3
NumPy Version: 1.26.4

In [3]:
from sqlalchemy import create_engine

print("SQLAlchemy Working Successfully")

SQLAlchemy Working Successfully

In [4]:
import pandas as pd

donors = pd.read_csv("../datasets/donors.csv")

donors.head()

  donor_id            name  age  gender blood_group  weight         city
0    D0001       Lila Mane   56    Male          A+      90    Ahmedabad
1    D0002    Hitesh Vohra   46    Male          A+      50       Rajkot
2    D0003      Ekiya Char   32  Female          B-      51  Gandhinagar
3    D0004  Tamanna Halder   25  Female          A+      78    Ahmedabad
4    D0005    Anay Mohanty   38    Male         AB-      82    Ahmedabad

In [5]:
donors.shape

(1000, 7)

In [6]:
donors.columns

Index(['donor_id', 'name', 'age', 'gender', 'blood_group', 'weight', 'city'], dtype='object')

In [7]:
donors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   donor_id     1000 non-null   object
 1   name         1000 non-null   object
 2   age          1000 non-null   int64
 3   gender       1000 non-null   object
 4   blood_group  1000 non-null   object
 5   weight       1000 non-null   int64
 6   city         1000 non-null   object
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [8]:
donors.isnull().sum()

donor_id       0
name           0
age            0
gender         0
blood_group    0
weight         0
city           0
dtype: int64

In [9]:
donors["blood_group"].value_counts()

blood_group
B-     143
A-     140
AB+    135
AB-    130
O+     125
A+     123
O-     104
B+     100
Name: count, dtype: int64

In [10]:
donors["age"].mean()

38.745

In [11]:
donors["city"].value_counts()

city
Ahmedabad      226
Vadodara       201
Gandhinagar    200
Surat          189
Rajkot         184
Name: count, dtype: int64

In [12]:
donors[donors["weight"] >= 50].shape

(1000, 7)

In [14]:
from sqlalchemy import create_engine

DATABASE_URL = "mysql+pymysql://root:12345@localhost/blood_bank"

engine = create_engine(DATABASE_URL)

print("Database Connected Successfully")

Database Connected Successfully

In [15]:
with engine.connect() as connection:
    print("Connection Successful")S

Connection Successful

In [16]:
donors.to_sql(
    name="donors",
    con=engine,
    if_exists="replace",
    index=False
)

print("Donors Imported Successfully")

Donors Imported Successfully

In [17]:
query = "SELECT * FROM donors LIMIT 5"

pd.read_sql(query, engine)

  donor_id            name  age  gender blood_group  weight         city
0    D0001       Lila Mane   56    Male          A+      90    Ahmedabad
1    D0002    Hitesh Vohra   46    Male          A+      50       Rajkot
2    D0003      Ekiya Char   32  Female          B-      51  Gandhinagar
3    D0004  Tamanna Halder   25  Female          A+      78    Ahmedabad
4    D0005    Anay Mohanty   38    Male         AB-      82    Ahmedabad

In [18]:
patients = pd.read_csv("../datasets/patients.csv")

patients.to_sql(
    name="patients",
    con=engine,
    if_exists="replace",
    index=False
)

print("Patients Imported")

Patients Imported

In [19]:
pd.read_sql(
    "SELECT * FROM patients LIMIT 5",
    engine
)

  patient_id    patient_name blood_group hospital_id
0     P00001   Chatura Comar          B+        H017
1     P00002      Kamala Sen         AB+        H037
2     P00003  Alexander Sant          B+        H012
3     P00004     Xavier Kota          O-        H006
4     P00005    Damini Joshi          B-        H022

In [20]:
hospitals = pd.read_csv("../datasets/hospitals.csv")

hospitals.to_sql(
    name="hospitals",
    con=engine,
    if_exists="replace",
    index=False
)

50

In [21]:
pd.read_sql(
    "SELECT * FROM hospitals LIMIT 5",
    engine
)

  hospital_id                           hospital_name       city
0        H001                     Kalita LLC Hospital      Surat
1        H002                 Sundaram Group Hospital   Vadodara
2        H003     Kurian, De and Subramaniam Hospital      Surat
3        H004    Bahri, Tailor and Mukherjee Hospital     Rajkot
4        H005  Jaggi, Mukhopadhyay and Comar Hospital  Ahmedabad

In [22]:
requests = pd.read_csv(
    "../datasets/blood_requests.csv"
)

requests.to_sql(
    name="blood_requests",
    con=engine,
    if_exists="replace",
    index=False
)

4000

In [23]:
pd.read_sql(
    "SELECT * FROM blood_requests LIMIT 5",
    engine
)

  request_id hospital_id blood_group  units_required emergency
0    BR00001        H004          B+               2    Medium
1    BR00002        H037          O-               3    Medium
2    BR00003        H004          O-               4    Medium
3    BR00004        H013         AB+               1      High
4    BR00005        H025         AB-               2    Medium

In [24]:
print(
    pd.read_sql(
        "SELECT COUNT(*) AS total FROM donors",
        engine
    )
)

print(
    pd.read_sql(
        "SELECT COUNT(*) AS total FROM patients",
        engine
    )
)

   total
0   1000
   total
0   3000

In [25]:
query = """
SELECT *
FROM donors
WHERE blood_group='O+'
"""

pd.read_sql(query, engine)

    donor_id            name  age  gender blood_group  weight         city
0      D0007    Jai Merchant   36    Male          O+      89    Ahmedabad
1      D0031   Tejas Kapadia   32  Female          O+      92     Vadodara
2      D0034    Gopal Prasad   24  Female          O+      73    Ahmedabad
3      D0039      Samar Raja   21  Female          O+      69  Gandhinagar
4      D0042    Ekaraj Balay   26  Female          O+      80    Ahmedabad
..       ...             ...  ...     ...         ...     ...          ...
120    D0944    Praneel Goda   59    Male          O+      66  Gandhinagar
121    D0947   Yutika Kurian   57  Female          O+      89     Vadodara
122    D0950     Amol Sarkar   57  Female          O+      68        Surat
123    D0970  Timothy D’Alia   25    Male          O+      54     Vadodara
124    D0974  Yashoda Sastry   50    Male          O+      61     Vadodara

[125 rows x 7 columns]

In [26]:
query = """
SELECT *
FROM donors
WHERE city='Ahmedabad'
"""

pd.read_sql(query, engine)

    donor_id            name  age  gender blood_group  weight       city
0      D0001       Lila Mane   56    Male          A+      90  Ahmedabad
1      D0004  Tamanna Halder   25  Female          A+      78  Ahmedabad
2      D0005    Anay Mohanty   38    Male         AB-      82  Ahmedabad
3      D0006  Ekantika Dubey   56  Female          O-      59  Ahmedabad
4      D0007    Jai Merchant   36    Male          O+      89  Ahmedabad
..       ...             ...  ...     ...         ...     ...        ...
221    D0985   Darika Luthra   21    Male          B+      60  Ahmedabad
222    D0986    Ikshita Gaba   39    Male          A+      82  Ahmedabad
223    D0990       Avi Devan   27    Male         AB-      76  Ahmedabad
224    D0995     Priya Mital   53    Male          A+      67  Ahmedabad
225    D1000   Gaurangi Saha   22  Female          A+      84  Ahmedabad

[226 rows x 7 columns]

In [27]:
query = """
SELECT *
FROM donors
WHERE blood_group='O+'
AND city='Ahmedabad'
"""

pd.read_sql(query, engine)

   donor_id                 name  age  gender blood_group  weight       city
0     D0007         Jai Merchant   36    Male          O+      89  Ahmedabad
1     D0034         Gopal Prasad   24  Female          O+      73  Ahmedabad
2     D0042         Ekaraj Balay   26  Female          O+      80  Ahmedabad
3     D0129            Jeet Sama   59  Female          O+      78  Ahmedabad
4     D0227       Theodore Yadav   56    Male          O+      83  Ahmedabad
5     D0229         Fariq Narula   57  Female          O+      67  Ahmedabad
6     D0268      Patrick Sanghvi   46  Female          O+      62  Ahmedabad
7     D0312         Qadim Halder   58    Male          O+      56  Ahmedabad
8     D0344       Shivani Chahal   46    Male          O+      64  Ahmedabad
9     D0345          Logan Konda   59    Male          O+      56  Ahmedabad
10    D0391        Brinda Sarkar   45  Female          O+      59  Ahmedabad
11    D0407         Manan Sarraf   22    Male          O+      53  Ahmedabad
12    D0415     Vrishti Kulkarni   39    Male          O+      63  Ahmedabad
13    D0422      Chakrika Butala   29    Male          O+      74  Ahmedabad
14    D0485       Advaith Butala   42  Female          O+      79  Ahmedabad
15    D0506         Lopa Shankar   52  Female          O+      58  Ahmedabad
16    D0530        Hemani Tandon   42    Male          O+      84  Ahmedabad
17    D0657       Krishna Sangha   28  Female          O+      81  Ahmedabad
18    D0682        Gautam Savant   27  Female          O+      61  Ahmedabad
19    D0721            Wazir Rai   47    Male          O+      69  Ahmedabad
20    D0772           Peter Wali   18  Female          O+      79  Ahmedabad
21    D0777  Indrajit Srinivasan   51    Male          O+      68  Ahmedabad
22    D0823         Chavvi Basak   21  Female          O+      74  Ahmedabad
23    D0855         Pranav Patla   48    Male          O+      77  Ahmedabad
24    D0871          Xavier Kibe   19    Male          O+      76  Ahmedabad
25    D0887          Samarth Som   31    Male          O+      60  Ahmedabad
26    D0904           Tarak Wali   37    Male          O+      72  Ahmedabad
27    D0918   Jagvi Mukhopadhyay   31    Male          O+      90  Ahmedabad
28    D0937         Rushil Sarin   54  Female          O+      77  Ahmedabad

Search Function

In [28]:
def find_donor(blood_group, city):

    query = f"""
    SELECT *
    FROM donors
    WHERE blood_group='{blood_group}'
    AND city='{city}'
    """

    return pd.read_sql(query, engine)

In [29]:
find_donor("O+", "Ahmedabad")

   donor_id                 name  age  gender blood_group  weight       city
0     D0007         Jai Merchant   36    Male          O+      89  Ahmedabad
1     D0034         Gopal Prasad   24  Female          O+      73  Ahmedabad
2     D0042         Ekaraj Balay   26  Female          O+      80  Ahmedabad
3     D0129            Jeet Sama   59  Female          O+      78  Ahmedabad
4     D0227       Theodore Yadav   56    Male          O+      83  Ahmedabad
5     D0229         Fariq Narula   57  Female          O+      67  Ahmedabad
6     D0268      Patrick Sanghvi   46  Female          O+      62  Ahmedabad
7     D0312         Qadim Halder   58    Male          O+      56  Ahmedabad
8     D0344       Shivani Chahal   46    Male          O+      64  Ahmedabad
9     D0345          Logan Konda   59    Male          O+      56  Ahmedabad
10    D0391        Brinda Sarkar   45  Female          O+      59  Ahmedabad
11    D0407         Manan Sarraf   22    Male          O+      53  Ahmedabad
12    D0415     Vrishti Kulkarni   39    Male          O+      63  Ahmedabad
13    D0422      Chakrika Butala   29    Male          O+      74  Ahmedabad
14    D0485       Advaith Butala   42  Female          O+      79  Ahmedabad
15    D0506         Lopa Shankar   52  Female          O+      58  Ahmedabad
16    D0530        Hemani Tandon   42    Male          O+      84  Ahmedabad
17    D0657       Krishna Sangha   28  Female          O+      81  Ahmedabad
18    D0682        Gautam Savant   27  Female          O+      61  Ahmedabad
19    D0721            Wazir Rai   47    Male          O+      69  Ahmedabad
20    D0772           Peter Wali   18  Female          O+      79  Ahmedabad
21    D0777  Indrajit Srinivasan   51    Male          O+      68  Ahmedabad
22    D0823         Chavvi Basak   21  Female          O+      74  Ahmedabad
23    D0855         Pranav Patla   48    Male          O+      77  Ahmedabad
24    D0871          Xavier Kibe   19    Male          O+      76  Ahmedabad
25    D0887          Samarth Som   31    Male          O+      60  Ahmedabad
26    D0904           Tarak Wali   37    Male          O+      72  Ahmedabad
27    D0918   Jagvi Mukhopadhyay   31    Male          O+      90  Ahmedabad
28    D0937         Rushil Sarin   54  Female          O+      77  Ahmedabad

In [30]:
query = """
SELECT
blood_group,
COUNT(*) AS total
FROM donors
GROUP BY blood_group
"""

pd.read_sql(query, engine)

  blood_group  total
0          A+    123
1          B-    143
2         AB-    130
3          O-    104
4          O+    125
5          A-    140
6         AB+    135
7          B+    100

In [31]:
query = """
SELECT
city,
COUNT(*) AS total
FROM donors
GROUP BY city
"""

pd.read_sql(query, engine)

          city  total
0    Ahmedabad    226
1       Rajkot    184
2  Gandhinagar    200
3     Vadodara    201
4        Surat    189