In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [3]:
DATABASE_URL = "mysql+pymysql://root:12345@localhost/blood_bank"

engine = create_engine(DATABASE_URL)

print("Connected Successfully")

Connected Successfully

In [4]:
donors = pd.read_sql(
    "SELECT * FROM donors",
    engine
)

donors.head()

  donor_id            name  age  gender blood_group  weight         city
0    D0001       Lila Mane   56    Male          A+      90    Ahmedabad
1    D0002    Hitesh Vohra   46    Male          A+      50       Rajkot
2    D0003      Ekiya Char   32  Female          B-      51  Gandhinagar
3    D0004  Tamanna Halder   25  Female          A+      78    Ahmedabad
4    D0005    Anay Mohanty   38    Male         AB-      82    Ahmedabad

In [5]:
blood_bags = pd.DataFrame({
    "bag_id":[f"BB{i:05d}" for i in range(1,1001)],
    "donor_id":donors["donor_id"],
    "blood_group":donors["blood_group"],
    "status":"Available"
})

blood_bags.head()

    bag_id donor_id blood_group     status
0  BB00001    D0001          A+  Available
1  BB00002    D0002          A+  Available
2  BB00003    D0003          B-  Available
3  BB00004    D0004          A+  Available
4  BB00005    D0005         AB-  Available

In [6]:
blood_bags["collection_date"] = pd.to_datetime(
    "2026-01-01"
) + pd.to_timedelta(
    np.random.randint(0,180,len(blood_bags)),
    unit="D"
)

In [7]:
blood_bags.head()

    bag_id donor_id blood_group     status collection_date
0  BB00001    D0001          A+  Available      2026-03-06
1  BB00002    D0002          A+  Available      2026-04-18
2  BB00003    D0003          B-  Available      2026-02-02
3  BB00004    D0004          A+  Available      2026-03-08
4  BB00005    D0005         AB-  Available      2026-04-26

In [8]:
blood_bags["expiry_date"] = (
    blood_bags["collection_date"]
    + pd.Timedelta(days=42)
)

In [9]:
blood_bags.head()

    bag_id donor_id blood_group     status collection_date expiry_date
0  BB00001    D0001          A+  Available      2026-03-06  2026-04-17
1  BB00002    D0002          A+  Available      2026-04-18  2026-05-30
2  BB00003    D0003          B-  Available      2026-02-02  2026-03-16
3  BB00004    D0004          A+  Available      2026-03-08  2026-04-19
4  BB00005    D0005         AB-  Available      2026-04-26  2026-06-07

In [10]:
blood_bags["status"] = np.random.choice(
    [
        "Available",
        "Issued",
        "Expired"
    ],
    size=len(blood_bags),
    p=[0.7,0.2,0.1]
)

In [11]:
blood_bags["status"].value_counts()

status
Available    694
Issued       193
Expired      113
Name: count, dtype: int64

In [12]:
blood_bags.to_sql(
    "blood_bags",
    engine,
    if_exists="replace",
    index=False
)

print("Blood Bags Imported")

Blood Bags Imported

In [13]:
pd.read_sql(
    "SELECT * FROM blood_bags LIMIT 5",
    engine
)

    bag_id donor_id blood_group     status collection_date expiry_date
0  BB00001    D0001          A+  Available      2026-03-06  2026-04-17
1  BB00002    D0002          A+  Available      2026-04-18  2026-05-30
2  BB00003    D0003          B-     Issued      2026-02-02  2026-03-16
3  BB00004    D0004          A+  Available      2026-03-08  2026-04-19
4  BB00005    D0005         AB-  Available      2026-04-26  2026-06-07

In [14]:
inventory = blood_bags[
    blood_bags["status"]=="Available"
]

inventory_summary = (
    inventory
    .groupby("blood_group")
    .size()
    .reset_index(name="units_available")
)

inventory_summary

  blood_group  units_available
0          A+               93
1          A-               88
2         AB+               84
3         AB-               90
4          B+               73
5          B-              104
6          O+               90
7          O-               72

In [15]:
inventory_summary.to_sql(
    "blood_inventory",
    engine,
    if_exists="replace",
    index=False
)

8

In [16]:
pd.read_sql(
    """
    SELECT *
    FROM blood_inventory
    """,
    engine
)

  blood_group  units_available
0          A+               93
1          A-               88
2         AB+               84
3         AB-               90
4          B+               73
5          B-              104
6          O+               90
7          O-               72

Blood Availability Function

In [17]:
def check_stock(blood_group):

    query = f"""
    SELECT *
    FROM blood_inventory
    WHERE blood_group='{blood_group}'
    """

    return pd.read_sql(query, engine)

In [18]:
check_stock("O+")

  blood_group  units_available
0          O+               90

Available Blood Bags

In [19]:
def find_blood_bags(blood_group):

    query = f"""
    SELECT *
    FROM blood_bags
    WHERE blood_group='{blood_group}'
    AND status='Available'
    """

    return pd.read_sql(query, engine)

In [20]:
find_blood_bags("B+")

     bag_id donor_id blood_group     status collection_date expiry_date
0   BB00046    D0046          B+  Available      2026-06-12  2026-07-24
1   BB00049    D0049          B+  Available      2026-06-20  2026-08-01
2   BB00068    D0068          B+  Available      2026-01-25  2026-03-08
3   BB00071    D0071          B+  Available      2026-04-10  2026-05-22
4   BB00080    D0080          B+  Available      2026-02-20  2026-04-03
..      ...      ...         ...        ...             ...         ...
64  BB00880    D0880          B+  Available      2026-06-04  2026-07-16
65  BB00888    D0888          B+  Available      2026-05-29  2026-07-10
66  BB00890    D0890          B+  Available      2026-01-18  2026-03-01
67  BB00940    D0940          B+  Available      2026-02-22  2026-04-05
68  BB00985    D0985          B+  Available      2026-03-28  2026-05-09

[69 rows x 6 columns]

In [21]:
pd.read_sql(
    """
    SELECT COUNT(*) AS total_bags
    FROM blood_bags
    """,
    engine
)

   total_bags
0        1000

In [22]:
pd.read_sql(
    """
    SELECT COUNT(*) AS available
    FROM blood_bags
    WHERE status='Available'
    """,
    engine
)

   available
0        680

In [23]:
pd.read_sql(
    """
    SELECT COUNT(*) AS expired
    FROM blood_bags
    WHERE status='Expired'
    """,
    engine
)

   expired
0      101

In [19]:
inventory = pd.read_sql(
    "SELECT * FROM blood_inventory",
    engine
)

inventory

  blood_group  units_available
0          A+               93
1          A-               88
2         AB+               84
3         AB-               90
4          B+               73
5          B-              104
6          O+               90
7          O-               72

Blood Requests

In [20]:
requests = pd.read_sql(
    "SELECT * FROM blood_requests LIMIT 10",
    engine
)

requests

  request_id hospital_id blood_group  units_required emergency
0    BR00001        H004          B+               2    Medium
1    BR00002        H037          O-               3    Medium
2    BR00003        H004          O-               4    Medium
3    BR00004        H013         AB+               1      High
4    BR00005        H025         AB-               2    Medium
5    BR00006        H013          O-               1    Medium
6    BR00007        H018          O-               4      High
7    BR00008        H024          A-               5       Low
8    BR00009        H002          A-               5    Medium
9    BR00010        H048          B-               2      High

In [ ]:
Allocation Function

In [21]:
def allocate_blood(
        blood_group,
        units_required):

    query = f"""
    SELECT *
    FROM blood_bags
    WHERE blood_group='{blood_group}'
    AND status='Available'
    LIMIT {units_required}
    """

    bags = pd.read_sql(query, engine)

    return bags

In [22]:
allocate_blood("O+",3)

    bag_id donor_id blood_group     status collection_date expiry_date
0  BB00007    D0007          O+  Available      2026-04-22  2026-06-03
1  BB00031    D0031          O+  Available      2026-05-31  2026-07-12
2  BB00034    D0034          O+  Available      2026-03-13  2026-04-24

In [23]:
def issue_blood_bags(bag_ids):

    for bag in bag_ids:

        query = f"""
        UPDATE blood_bags
        SET status='Issued'
        WHERE bag_id='{bag}'
        """

        with engine.begin() as conn:
            conn.execute(query)

In [24]:
bags = allocate_blood("O+",3)

bag_ids = bags["bag_id"].tolist()

bag_ids

['BB00007', 'BB00031', 'BB00034']

In [25]:
from sqlalchemy import text

with engine.begin() as conn:

    for bag in bag_ids:

        conn.execute(
            text("""
            UPDATE blood_bags
            SET status='Issued'
            WHERE bag_id=:bag
            """),
            {"bag":bag}
        )

In [26]:
pd.read_sql(
    """
    SELECT *
    FROM blood_bags
    WHERE bag_id IN
    ('BB001','BB005','BB010')
    """,
    engine
)

Empty DataFrame
Columns: [bag_id, donor_id, blood_group, status, collection_date, expiry_date]
Index: []

In [27]:
blood_bags = pd.read_sql(
    "SELECT * FROM blood_bags",
    engine
)

inventory = blood_bags[
    blood_bags["status"]=="Available"
]

inventory_summary = (
    inventory
    .groupby("blood_group")
    .size()
    .reset_index(name="units_available")
)

In [28]:
inventory_summary.to_sql(
    "blood_inventory",
    engine,
    if_exists="replace",
    index=False
)

8

In [29]:
pd.read_sql(
    "SELECT * FROM blood_inventory",
    engine
)

  blood_group  units_available
0          A+               93
1          A-               88
2         AB+               84
3         AB-               90
4          B+               73
5          B-              104
6          O+               87
7          O-               72

In [30]:
def process_request(
        blood_group,
        units_required):

    query = f"""
    SELECT *
    FROM blood_bags
    WHERE blood_group='{blood_group}'
    AND status='Available'
    LIMIT {units_required}
    """

    bags = pd.read_sql(query, engine)

    if len(bags) < units_required:

        return "Not Enough Blood Available"

    return bags

In [31]:
process_request("B+",5)

    bag_id donor_id blood_group     status collection_date expiry_date
0  BB00046    D0046          B+  Available      2026-06-24  2026-08-05
1  BB00049    D0049          B+  Available      2026-06-29  2026-08-10
2  BB00068    D0068          B+  Available      2026-05-05  2026-06-16
3  BB00080    D0080          B+  Available      2026-04-09  2026-05-21
4  BB00086    D0086          B+  Available      2026-04-30  2026-06-11

In [32]:
request_history = pd.DataFrame(
    columns=[
        "request_id",
        "hospital_id",
        "blood_group",
        "units_required",
        "status"
    ]
)

In [33]:
request_history.to_sql(
    "request_history",
    engine,
    if_exists="replace",
    index=False
)

0

In [34]:
pd.read_sql(
"""
SELECT
SUM(units_available)
AS total
FROM blood_inventory
""",
engine
)

   total
0  691.0

In [35]:
pd.read_sql(
"""
SELECT COUNT(*)
AS issued
FROM blood_bags
WHERE status='Issued'
""",
engine
)

   issued
0     196

In [36]:
pd.read_sql(
"""
SELECT COUNT(*)
AS expired
FROM blood_bags
WHERE status='Expired'
""",
engine
)

   expired
0      113

In [37]:
patients = pd.read_sql(
    "SELECT * FROM patients",
    engine
)

blood_bags = pd.read_sql(
    "SELECT * FROM blood_bags",
    engine
)

donors = pd.read_sql(
    "SELECT * FROM donors",
    engine
)

In [38]:
patients.head()
blood_bags.head()
donors.head()

  donor_id            name  age  gender blood_group  weight         city
0    D0001       Lila Mane   56    Male          A+      90    Ahmedabad
1    D0002    Hitesh Vohra   46    Male          A+      50       Rajkot
2    D0003      Ekiya Char   32  Female          B-      51  Gandhinagar
3    D0004  Tamanna Halder   25  Female          A+      78    Ahmedabad
4    D0005    Anay Mohanty   38    Male         AB-      82    Ahmedabad

In [39]:
blood_usage = pd.DataFrame(columns=[
    "usage_id",
    "patient_id",
    "bag_id",
    "donor_id",
    "date_used"
])

blood_usage.head()

Empty DataFrame
Columns: [usage_id, patient_id, bag_id, donor_id, date_used]
Index: []

In [40]:
issued_bags = blood_bags[
    blood_bags["status"] == "Issued"
]

issued_bags.head()

     bag_id donor_id blood_group  status collection_date expiry_date
2   BB00003    D0003          B-  Issued      2026-02-02  2026-03-16
5   BB00006    D0006          O-  Issued      2026-04-22  2026-06-03
6   BB00007    D0007          O+  Issued      2026-04-22  2026-06-03
14  BB00015    D0015          O-  Issued      2026-05-11  2026-06-22
16  BB00017    D0017          A-  Issued      2026-01-19  2026-03-02

In [41]:
import numpy as np

blood_usage = pd.DataFrame({
    "usage_id":[f"U{i:05d}" for i in range(1,len(issued_bags)+1)],
    "patient_id":np.random.choice(
        patients["patient_id"],
        len(issued_bags)
    ),
    "bag_id":issued_bags["bag_id"].values,
    "donor_id":issued_bags["donor_id"].values,
    "date_used":"2026-06-15"
})

In [42]:
blood_usage.to_sql(
    "blood_usage",
    engine,
    if_exists="replace",
    index=False
)

print("Blood Usage Saved")

Blood Usage Saved

In [43]:
pd.read_sql(
    "SELECT * FROM blood_usage LIMIT 10",
    engine
)

  usage_id patient_id   bag_id donor_id   date_used
0   U00001     P02043  BB00003    D0003  2026-06-15
1   U00002     P00153  BB00006    D0006  2026-06-15
2   U00003     P02960  BB00007    D0007  2026-06-15
3   U00004     P01468  BB00015    D0015  2026-06-15
4   U00005     P01630  BB00017    D0017  2026-06-15
5   U00006     P00319  BB00018    D0018  2026-06-15
6   U00007     P01509  BB00025    D0025  2026-06-15
7   U00008     P00701  BB00031    D0031  2026-06-15
8   U00009     P00137  BB00033    D0033  2026-06-15
9   U00010     P01884  BB00034    D0034  2026-06-15

In [44]:
def patient_history(patient_id):

    query = f"""
    SELECT *
    FROM blood_usage
    WHERE patient_id='{patient_id}'
    """

    return pd.read_sql(query, engine)

In [45]:
patient_history("P00021")

Empty DataFrame
Columns: [usage_id, patient_id, bag_id, donor_id, date_used]
Index: []

In [46]:
def donor_impact(donor_id):

    query = f"""
    SELECT *
    FROM blood_usage
    WHERE donor_id='{donor_id}'
    """

    return pd.read_sql(query, engine)

In [47]:
donor_impact("D0005")

Empty DataFrame
Columns: [usage_id, patient_id, bag_id, donor_id, date_used]
Index: []

In [48]:
query = """
SELECT
patient_id,
COUNT(*) AS bags_received
FROM blood_usage
GROUP BY patient_id
ORDER BY bags_received DESC
"""

pd.read_sql(query, engine)

    patient_id  bags_received
0       P00367              2
1       P00726              2
2       P02284              2
3       P02888              2
4       P01860              2
..         ...            ...
184     P02736              1
185     P00781              1
186     P02446              1
187     P01908              1
188     P02998              1

[189 rows x 2 columns]

In [49]:
query = """
SELECT
donor_id,
COUNT(DISTINCT patient_id)
AS patients_helped
FROM blood_usage
GROUP BY donor_id
ORDER BY patients_helped DESC
"""

pd.read_sql(query, engine)

    donor_id  patients_helped
0      D0003                1
1      D0006                1
2      D0007                1
3      D0015                1
4      D0017                1
..       ...              ...
191    D0983                1
192    D0984                1
193    D0992                1
194    D0996                1
195    D1000                1

[196 rows x 2 columns]

In [50]:
query = """
SELECT
bu.patient_id,
bu.bag_id,
bu.donor_id
FROM blood_usage bu
"""

pd.read_sql(query, engine)

    patient_id   bag_id donor_id
0       P02043  BB00003    D0003
1       P00153  BB00006    D0006
2       P02960  BB00007    D0007
3       P01468  BB00015    D0015
4       P01630  BB00017    D0017
..         ...      ...      ...
191     P00781  BB00983    D0983
192     P00367  BB00984    D0984
193     P02446  BB00992    D0992
194     P01908  BB00996    D0996
195     P02998  BB01000    D1000

[196 rows x 3 columns]

In [51]:
notification_data = pd.read_sql("""
SELECT
donor_id,
COUNT(*) AS blood_bags_used
FROM blood_usage
GROUP BY donor_id
""", engine)

notification_data.head()

  donor_id  blood_bags_used
0    D0003                1
1    D0006                1
2    D0007                1
3    D0015                1
4    D0017                1

In [52]:
pd.read_sql("""
SELECT COUNT(*) AS total_used
FROM blood_usage
""", engine)

   total_used
0         196

In [53]:
pd.read_sql("""
SELECT COUNT(DISTINCT patient_id)
AS patients_served
FROM blood_usage
""", engine)

   patients_served
0              189

In [54]:
pd.read_sql("""
SELECT COUNT(DISTINCT donor_id)
AS donors
FROM blood_usage
""", engine)

   donors
0     196