In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
DATABASE_URL = "mysql+pymysql://root:12345@localhost/blood_bank"

engine = create_engine(DATABASE_URL)

print("Database Connected")

Database Connected

In [3]:
blood_requests = pd.read_sql(
    "SELECT * FROM blood_requests",
    engine
)

blood_inventory = pd.read_sql(
    "SELECT * FROM blood_inventory",
    engine
)

blood_requests.head()

  request_id hospital_id blood_group  units_required emergency
0    BR00001        H004          B+               2    Medium
1    BR00002        H037          O-               3    Medium
2    BR00003        H004          O-               4    Medium
3    BR00004        H013         AB+               1      High
4    BR00005        H025         AB-               2    Medium

In [4]:
blood_requests.shape

(4000, 5)

In [5]:
blood_requests["blood_group"].value_counts()

blood_group
O-     519
AB-    517
A-     514
O+     511
B-     505
AB+    491
A+     475
B+     468
Name: count, dtype: int64

In [6]:
blood_requests.groupby(
    "blood_group"
)["units_required"].sum()

blood_group
A+     1404
A-     1568
AB+    1447
AB-    1512
B+     1357
B-     1522
O+     1556
O-     1534
Name: units_required, dtype: int64

In [7]:
demand_summary = blood_requests.groupby(
    "blood_group"
)["units_required"].sum().reset_index()

demand_summary.columns = [
    "blood_group",
    "total_requested_units"
]

demand_summary

  blood_group  total_requested_units
0          A+                   1404
1          A-                   1568
2         AB+                   1447
3         AB-                   1512
4          B+                   1357
5          B-                   1522
6          O+                   1556
7          O-                   1534

In [8]:
demand_summary.to_sql(
    "demand_summary",
    engine,
    if_exists="replace",
    index=False
)

8

In [9]:
analysis = demand_summary.merge(
    blood_inventory,
    on="blood_group"
)

analysis.head()

  blood_group  total_requested_units  units_available
0          A+                   1404               93
1          A-                   1568               88
2         AB+                   1447               84
3         AB-                   1512               90
4          B+                   1357               73

Calculate Demand Gap

In [10]:
analysis["demand_gap"] = (
    analysis["total_requested_units"]
    - analysis["units_available"]
)

In [11]:
analysis

  blood_group  total_requested_units  units_available  demand_gap
0          A+                   1404               93        1311
1          A-                   1568               88        1480
2         AB+                   1447               84        1363
3         AB-                   1512               90        1422
4          B+                   1357               73        1284
5          B-                   1522              104        1418
6          O+                   1556               87        1469
7          O-                   1534               72        1462

In [12]:
def risk_level(gap):

    if gap > 100:
        return "High"

    elif gap > 50:
        return "Medium"

    else:
        return "Low"

In [13]:
analysis["risk_level"] = (
    analysis["demand_gap"]
    .apply(risk_level)
)

In [14]:
analysis[
    analysis["risk_level"]=="High"
]

  blood_group  total_requested_units  units_available  demand_gap risk_level
0          A+                   1404               93        1311       High
1          A-                   1568               88        1480       High
2         AB+                   1447               84        1363       High
3         AB-                   1512               90        1422       High
4          B+                   1357               73        1284       High
5          B-                   1522              104        1418       High
6          O+                   1556               87        1469       High
7          O-                   1534               72        1462       High

In [15]:
prediction = (
    blood_requests
    .groupby("blood_group")
    ["units_required"]
    .mean()
    .reset_index()
)

prediction.columns = [
    "blood_group",
    "predicted_monthly_demand"
]

prediction

  blood_group  predicted_monthly_demand
0          A+                  2.955789
1          A-                  3.050584
2         AB+                  2.947047
3         AB-                  2.924565
4          B+                  2.899573
5          B-                  3.013861
6          O+                  3.045010
7          O-                  2.955684

In [16]:
prediction.to_sql(
    "blood_demand_prediction",
    engine,
    if_exists="replace",
    index=False
)

8

Prediction Function

In [17]:
def predict_demand(blood_group):

    query = f"""
    SELECT *
    FROM blood_demand_prediction
    WHERE blood_group='{blood_group}'
    """

    return pd.read_sql(query, engine)

In [18]:
predict_demand("O+")

  blood_group  predicted_monthly_demand
0          O+                   3.04501

In [19]:
shortage_alerts = analysis[
    analysis["risk_level"]=="High"
]

shortage_alerts

  blood_group  total_requested_units  units_available  demand_gap risk_level
0          A+                   1404               93        1311       High
1          A-                   1568               88        1480       High
2         AB+                   1447               84        1363       High
3         AB-                   1512               90        1422       High
4          B+                   1357               73        1284       High
5          B-                   1522              104        1418       High
6          O+                   1556               87        1469       High
7          O-                   1534               72        1462       High

Alert Messages

In [20]:
for index,row in shortage_alerts.iterrows():

    print(
        f"""
WARNING

Blood Group: {row['blood_group']}

Demand Gap: {row['demand_gap']}

Risk Level: {row['risk_level']}
"""
    )

WARNING

Blood Group: A+

Demand Gap: 1311

Risk Level: High


WARNING

Blood Group: A-

Demand Gap: 1480

Risk Level: High


WARNING

Blood Group: AB+

Demand Gap: 1363

Risk Level: High


WARNING

Blood Group: AB-

Demand Gap: 1422

Risk Level: High


WARNING

Blood Group: B+

Demand Gap: 1284

Risk Level: High


WARNING

Blood Group: B-

Demand Gap: 1418

Risk Level: High


WARNING

Blood Group: O+

Demand Gap: 1469

Risk Level: High


WARNING

Blood Group: O-

Demand Gap: 1462

Risk Level: High

In [21]:
report = analysis[
    [
        "blood_group",
        "total_requested_units",
        "units_available",
        "demand_gap",
        "risk_level"
    ]
]

report

  blood_group  total_requested_units  units_available  demand_gap risk_level
0          A+                   1404               93        1311       High
1          A-                   1568               88        1480       High
2         AB+                   1447               84        1363       High
3         AB-                   1512               90        1422       High
4          B+                   1357               73        1284       High
5          B-                   1522              104        1418       High
6          O+                   1556               87        1469       High
7          O-                   1534               72        1462       High

In [22]:
report.to_sql(
    "analytics_report",
    engine,
    if_exists="replace",
    index=False
)

8

In [23]:
blood_requests.groupby(
    "blood_group"
)["units_required"].sum().idxmax()

'A-'

In [24]:
blood_requests["units_required"].sum()

11900

In [25]:
analysis.sort_values(
    "demand_gap",
    ascending=False
).head(1)

  blood_group  total_requested_units  units_available  demand_gap risk_level
1          A-                   1568               88        1480       High