In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import datetime,timedelta

In [2]:
DATABASE_URL = "mysql+pymysql://root:12345@localhost/blood_bank"

engine = create_engine(DATABASE_URL)

print("Database Connected")

Database Connected

In [3]:
donors = pd.read_sql(
    "SELECT * FROM donors",
    engine
)

donors.head()

  donor_id            name  age  gender blood_group  weight         city
0    D0001       Lila Mane   56    Male          A+      90    Ahmedabad
1    D0002    Hitesh Vohra   46    Male          A+      50       Rajkot
2    D0003      Ekiya Char   32  Female          B-      51  Gandhinagar
3    D0004  Tamanna Halder   25  Female          A+      78    Ahmedabad
4    D0005    Anay Mohanty   38    Male         AB-      82    Ahmedabad

In [4]:
donors.columns

Index(['donor_id', 'name', 'age', 'gender', 'blood_group', 'weight', 'city'], dtype='object')

In [5]:
health_reports = pd.DataFrame({
    "report_id":[f"HR{i:05d}" for i in range(1,len(donors)+1)],
    "donor_id":donors["donor_id"],
    "hemoglobin":np.random.uniform(10,18,len(donors)).round(1),
    "weight":np.random.randint(40,90,len(donors)),
    "systolic_bp":np.random.randint(90,140,len(donors)),
    "diastolic_bp":np.random.randint(60,90,len(donors)),
    "pulse":np.random.randint(60,100,len(donors))
})

health_reports.head()

  report_id donor_id  hemoglobin  weight  systolic_bp  diastolic_bp  pulse
0   HR00001    D0001        12.0      82          109            80     79
1   HR00002    D0002        17.4      89          106            81     86
2   HR00003    D0003        10.5      59          123            80     97
3   HR00004    D0004        13.7      75          108            75     93
4   HR00005    D0005        12.4      71          130            60     92

In [6]:
health_reports.to_sql(
    "health_reports",
    engine,
    if_exists="replace",
    index=False
)

print("Health Reports Saved")

Health Reports Saved

In [7]:
pd.read_sql(
    "SELECT * FROM health_reports LIMIT 5",
    engine
)

  report_id donor_id  hemoglobin  weight  systolic_bp  diastolic_bp  pulse
0   HR00001    D0001        12.0      82          109            80     79
1   HR00002    D0002        17.4      89          106            81     86
2   HR00003    D0003        10.5      59          123            80     97
3   HR00004    D0004        13.7      75          108            75     93
4   HR00005    D0005        12.4      71          130            60     92

In [18]:
data = donors.merge(
    health_reports,
    on="donor_id"
)

data.rename(
    columns={
        "weight_x": "donor_weight",
        "weight_y": "report_weight"
    },
    inplace=True
)

print(data.columns)

Index(['donor_id', 'name', 'age', 'gender', 'blood_group', 'donor_weight',
       'city', 'report_id', 'hemoglobin', 'report_weight', 'systolic_bp',
       'diastolic_bp', 'pulse'],
      dtype='object')

Eligibility Function

In [9]:
def check_eligibility(age, weight, hemoglobin):

    if age < 18:
        return "Not Eligible"

    if age > 65:
        return "Not Eligible"

    if weight < 50:
        return "Not Eligible"

    if hemoglobin < 12.5:
        return "Not Eligible"

    return "Eligible"

In [19]:
data["eligibility"] = data.apply(
    lambda row: check_eligibility(
        row["age"],
        row["report_weight"],   # use report_weight
        row["hemoglobin"]
    ),
    axis=1
)

In [21]:
data["eligibility"].value_counts()

eligibility
Eligible        542
Not Eligible    458
Name: count, dtype: int64

In [25]:
data[[
    "donor_id",
    "age",
    "report_weight",
    "hemoglobin",
    "eligibility"
]].head()

  donor_id  age  report_weight  hemoglobin   eligibility
0    D0001   56             82        12.0  Not Eligible
1    D0002   46             89        17.4      Eligible
2    D0003   32             59        10.5  Not Eligible
3    D0004   25             75        13.7      Eligible
4    D0005   38             71        12.4  Not Eligible

In [26]:
data["eligibility"].value_counts()

eligibility
Eligible        542
Not Eligible    458
Name: count, dtype: int64

In [16]:
print(data.columns.tolist())

['donor_id', 'name', 'age', 'gender', 'blood_group', 'donor_weight', 'city', 'report_id', 'hemoglobin', 'report_weight', 'systolic_bp', 'diastolic_bp', 'pulse']

In [28]:
print(donors.columns.tolist())

['donor_id', 'name', 'age', 'gender', 'blood_group', 'weight', 'city']

In [30]:
import pandas as pd
import numpy as np

donors["last_donation_date"] = (
    pd.Timestamp("2026-01-01")
    + pd.to_timedelta(
        np.random.randint(0, 180, len(donors)),
        unit="D"
    )
)

In [31]:
donors.head()

,donor_id,name,age,gender,blood_group,weight,city,last_donation_date
0,D0001,Lila Mane,56,Male,A+,90,Ahmedabad,2026-04-04
1,D0002,Hitesh Vohra,46,Male,A+,50,Rajkot,2026-05-12
2,D0003,Ekiya Char,32,Female,B-,51,Gandhinagar,2026-05-04
3,D0004,Tamanna Halder,25,Female,A+,78,Ahmedabad,2026-03-22
4,D0005,Anay Mohanty,38,Male,AB-,82,Ahmedabad,2026-06-06

In [32]:
donors["last_donation_date"] = pd.to_datetime(
    donors["last_donation_date"]
)

donors["next_donation_date"] = (
    donors["last_donation_date"]
    + pd.Timedelta(days=90)
)

In [33]:
donors[[
    "donor_id",
    "last_donation_date",
    "next_donation_date"
]].head()

  donor_id last_donation_date next_donation_date
0    D0001         2026-04-04         2026-07-03
1    D0002         2026-05-12         2026-08-10
2    D0003         2026-05-04         2026-08-02
3    D0004         2026-03-22         2026-06-20
4    D0005         2026-06-06         2026-09-04

In [34]:
donors.to_sql(
    "donors",
    engine,
    if_exists="replace",
    index=False
)

print("Donors table updated successfully")

Donors table updated successfully

In [35]:
def donor_status(donor_id):

    query = f"""
    SELECT
    d.donor_id,
    d.age,
    h.weight,
    h.hemoglobin
    FROM donors d
    JOIN health_reports h
    ON d.donor_id=h.donor_id
    WHERE d.donor_id='{donor_id}'
    """

    return pd.read_sql(query, engine)

In [36]:
donor_status("D0001")

  donor_id  age  weight  hemoglobin
0    D0001   56      82        12.0

find eligible emergency donor

In [37]:
eligible_donors = data[
    data["eligibility"]=="Eligible"
]

eligible_donors.head()

,donor_id,name,age,gender,blood_group,donor_weight,city,report_id,hemoglobin,report_weight,systolic_bp,diastolic_bp,pulse,eligibility
1,D0002,Hitesh Vohra,46,Male,A+,50,Rajkot,HR00002,17.4,89,106,81,86,Eligible
3,D0004,Tamanna Halder,25,Female,A+,78,Ahmedabad,HR00004,13.7,75,108,75,93,Eligible
5,D0006,Ekantika Dubey,56,Female,O-,59,Ahmedabad,HR00006,15.0,87,103,88,90,Eligible
6,D0007,Jai Merchant,36,Male,O+,89,Ahmedabad,HR00007,13.2,61,115,81,71,Eligible
11,D0012,Champak Bawa,53,Female,B-,57,Gandhinagar,HR00012,15.5,76,137,78,76,Eligible

In [38]:
eligible_donors[
    eligible_donors["blood_group"]=="O+"
]

,donor_id,name,age,gender,blood_group,donor_weight,city,report_id,hemoglobin,report_weight,systolic_bp,diastolic_bp,pulse,eligibility
6,D0007,Jai Merchant,36,Male,O+,89,Ahmedabad,HR00007,13.2,61,115,81,71,Eligible
30,D0031,Tejas Kapadia,32,Female,O+,92,Vadodara,HR00031,14.9,55,96,85,75,Eligible
33,D0034,Gopal Prasad,24,Female,O+,73,Ahmedabad,HR00034,16.4,87,105,73,89,Eligible
54,D0055,Udarsh Ramachandran,19,Male,O+,59,Surat,HR00055,16.3,82,100,63,95,Eligible
68,D0069,Nathan Mitra,31,Male,O+,53,Gandhinagar,HR00069,15.5,63,113,69,93,Eligible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,D0931,Mason Kohli,58,Male,O+,70,Vadodara,HR00931,16.5,53,92,75,69,Eligible
936,D0937,Rushil Sarin,54,Female,O+,77,Ahmedabad,HR00937,17.0,75,99,86,91,Eligible
946,D0947,Yutika Kurian,57,Female,O+,89,Vadodara,HR00947,15.5,64,135,77,87,Eligible
949,D0950,Amol Sarkar,57,Female,O+,68,Surat,HR00950,14.1,50,116,65,96,Eligible
969,D0970,Timothy D’Alia,25,Male,O+,54,Vadodara,HR00970,15.3,61,119,72,65,Eligible

In [39]:
len(
    data[data["eligibility"]=="Eligible"]
)

542

In [40]:
len(
    data[data["eligibility"]=="Not Eligible"]
)

458

In [41]:
data["hemoglobin"].mean()

13.994200000000001

In [43]:
data["report_weight"].mean()

64.046

In [44]:
data.to_sql(
    "donor_eligibility",
    engine,
    if_exists="replace",
    index=False
)

1000

In [45]:
pd.read_sql(
    "SELECT * FROM donor_eligibility LIMIT 5",
    engine
)

,donor_id,name,age,gender,blood_group,donor_weight,city,report_id,hemoglobin,report_weight,systolic_bp,diastolic_bp,pulse,eligibility
0,D0001,Lila Mane,56,Male,A+,90,Ahmedabad,HR00001,12.0,82,109,80,79,Not Eligible
1,D0002,Hitesh Vohra,46,Male,A+,50,Rajkot,HR00002,17.4,89,106,81,86,Eligible
2,D0003,Ekiya Char,32,Female,B-,51,Gandhinagar,HR00003,10.5,59,123,80,97,Not Eligible
3,D0004,Tamanna Halder,25,Female,A+,78,Ahmedabad,HR00004,13.7,75,108,75,93,Eligible
4,D0005,Anay Mohanty,38,Male,AB-,82,Ahmedabad,HR00005,12.4,71,130,60,92,Not Eligible

create health report

In [46]:
def health_report(donor_id):

    query = f"""
    SELECT *
    FROM health_reports
    WHERE donor_id='{donor_id}'
    """

    return pd.read_sql(query, engine)

In [47]:
health_report("D0001")

  report_id donor_id  hemoglobin  weight  systolic_bp  diastolic_bp  pulse
0   HR00001    D0001        12.0      82          109            80     79

In [50]:
donors = pd.read_sql(
    "SELECT * FROM donors",
    engine
)

blood_usage = pd.read_sql(
    "SELECT * FROM blood_usage",
    engine
)

patients = pd.read_sql(
    "SELECT * FROM patients",
    engine
)

donor_eligibility = pd.read_sql(
    "SELECT * FROM donor_eligibility",
    engine
)

In [48]:
notifications = pd.DataFrame(columns=[
    "notification_id",
    "donor_id",
    "message",
    "notification_type",
    "date_sent"
])

notifications

Empty DataFrame
Columns: [notification_id, donor_id, message, notification_type, date_sent]
Index: []

In [51]:
blood_used_notifications = []

for index,row in blood_usage.iterrows():

    blood_used_notifications.append({
        "notification_id":f"N{index+1:05d}",
        "donor_id":row["donor_id"],
        "message":"Your blood donation was used to help a patient.",
        "notification_type":"Blood Used",
        "date_sent":datetime.now()
    })

blood_used_df = pd.DataFrame(
    blood_used_notifications
)

blood_used_df.head()

,notification_id,donor_id,message,notification_type,date_sent
0,N00001,D0003,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48.354270
1,N00002,D0006,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48.354270
2,N00003,D0007,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48.354270
3,N00004,D0015,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48.354270
4,N00005,D0017,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48.354270

In [52]:
blood_used_df.to_sql(
    "notifications",
    engine,
    if_exists="replace",
    index=False
)

print("Notifications Saved")

Notifications Saved

In [53]:
pd.read_sql(
    "SELECT * FROM notifications LIMIT 10",
    engine
)

,notification_id,donor_id,message,notification_type,date_sent
0,N00001,D0003,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48
1,N00002,D0006,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48
2,N00003,D0007,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48
3,N00004,D0015,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48
4,N00005,D0017,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48
5,N00006,D0018,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48
6,N00007,D0025,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48
7,N00008,D0031,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48
8,N00009,D0033,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48
9,N00010,D0034,Your blood donation was used to help a patient.,Blood Used,2026-06-19 21:34:48

donation reminder system

In [54]:
from datetime import datetime

today = pd.Timestamp.today()

eligible_again = donors[
    donors["next_donation_date"] <= today
]

eligible_again.head()

,donor_id,name,age,gender,blood_group,weight,city,last_donation_date,next_donation_date
7,D0008,Jatin Karnik,40,Male,O-,70,Vadodara,2026-02-15,2026-05-16
8,D0009,Parth Basu,28,Male,AB-,77,Vadodara,2026-02-27,2026-05-28
10,D0011,Vidhi Jani,41,Female,B-,83,Gandhinagar,2026-02-05,2026-05-06
11,D0012,Champak Bawa,53,Female,B-,57,Gandhinagar,2026-02-10,2026-05-11
12,D0013,Mitali Puri,57,Female,A+,71,Gandhinagar,2026-03-12,2026-06-10

In [55]:
reminders = []

for index,row in eligible_again.iterrows():

    reminders.append({
        "notification_id":f"R{index+1:05d}",
        "donor_id":row["donor_id"],
        "message":"You are eligible to donate blood again.",
        "notification_type":"Donation Reminder",
        "date_sent":datetime.now()
    })

reminder_df = pd.DataFrame(reminders)

In [56]:
all_notifications = pd.concat([
    blood_used_df,
    reminder_df
])

all_notifications.to_sql(
    "notifications",
    engine,
    if_exists="replace",
    index=False
)

655

In [57]:
emergency_request = {
    "blood_group":"O+",
    "city":"Ahmedabad"
}

In [58]:
eligible_donors = donor_eligibility[
    (donor_eligibility["blood_group"]=="O+") &
    (donor_eligibility["eligibility"]=="Eligible")
]

eligible_donors.head()

,donor_id,name,age,gender,blood_group,donor_weight,city,report_id,hemoglobin,report_weight,systolic_bp,diastolic_bp,pulse,eligibility
6,D0007,Jai Merchant,36,Male,O+,89,Ahmedabad,HR00007,13.2,61,115,81,71,Eligible
30,D0031,Tejas Kapadia,32,Female,O+,92,Vadodara,HR00031,14.9,55,96,85,75,Eligible
33,D0034,Gopal Prasad,24,Female,O+,73,Ahmedabad,HR00034,16.4,87,105,73,89,Eligible
54,D0055,Udarsh Ramachandran,19,Male,O+,59,Surat,HR00055,16.3,82,100,63,95,Eligible
68,D0069,Nathan Mitra,31,Male,O+,53,Gandhinagar,HR00069,15.5,63,113,69,93,Eligible

In [59]:
emergency_notifications = []

for index,row in eligible_donors.iterrows():

    emergency_notifications.append({
        "notification_id":f"E{index+1:05d}",
        "donor_id":row["donor_id"],
        "message":"Emergency blood requirement nearby. Please donate if possible.",
        "notification_type":"Emergency Alert",
        "date_sent":datetime.now()
    })

emergency_df = pd.DataFrame(
    emergency_notifications
)

In [60]:
final_notifications = pd.concat([
    all_notifications,
    emergency_df
])

final_notifications.to_sql(
    "notifications",
    engine,
    if_exists="replace",
    index=False
)

719

In [61]:
def donor_notifications(donor_id):

    query = f"""
    SELECT *
    FROM notifications
    WHERE donor_id='{donor_id}'
    """

    return pd.read_sql(query, engine)

In [62]:
donor_notifications("D0001")

Empty DataFrame
Columns: [notification_id, donor_id, message, notification_type, date_sent]
Index: []

In [63]:
pd.read_sql("""
SELECT
notification_type,
COUNT(*) as total
FROM notifications
GROUP BY notification_type
""", engine)

   notification_type  total
0         Blood Used    196
1  Donation Reminder    459
2    Emergency Alert     64

personlized blood usage message

In [64]:
def blood_used_message(donor_id):

    query = f"""
    SELECT COUNT(*)
    AS total
    FROM blood_usage
    WHERE donor_id='{donor_id}'
    """

    result = pd.read_sql(query, engine)

    count = result.iloc[0]["total"]

    return f"Your blood donation has helped {count} patient(s). Thank you!"

In [65]:
blood_used_message("D0001")

'Your blood donation has helped 0 patient(s). Thank you!'

In [67]:
donors = pd.read_sql(
    "SELECT * FROM donors",
    engine
)

eligibility = pd.read_sql(
    "SELECT * FROM donor_eligibility",
    engine
)

blood_usage = pd.read_sql(
    "SELECT * FROM blood_usage",
    engine
)

In [68]:
data = donors.merge(
    eligibility[
        ["donor_id","eligibility"]
    ],
    on="donor_id"
)

data.head()

,donor_id,name,age,gender,blood_group,weight,city,last_donation_date,next_donation_date,eligibility
0,D0001,Lila Mane,56,Male,A+,90,Ahmedabad,2026-04-04,2026-07-03,Not Eligible
1,D0002,Hitesh Vohra,46,Male,A+,50,Rajkot,2026-05-12,2026-08-10,Eligible
2,D0003,Ekiya Char,32,Female,B-,51,Gandhinagar,2026-05-04,2026-08-02,Not Eligible
3,D0004,Tamanna Halder,25,Female,A+,78,Ahmedabad,2026-03-22,2026-06-20,Eligible
4,D0005,Anay Mohanty,38,Male,AB-,82,Ahmedabad,2026-06-06,2026-09-04,Not Eligible

Emergency Reqeat

In [69]:
emergency_request = {
    "blood_group":"O+",
    "city":"Ahmedabad",
    "units_required":3
}

In [70]:
matching = data[
    data["blood_group"] ==
    emergency_request["blood_group"]
]

matching.head()

,donor_id,name,age,gender,blood_group,weight,city,last_donation_date,next_donation_date,eligibility
6,D0007,Jai Merchant,36,Male,O+,89,Ahmedabad,2026-05-04,2026-08-02,Eligible
30,D0031,Tejas Kapadia,32,Female,O+,92,Vadodara,2026-04-04,2026-07-03,Eligible
33,D0034,Gopal Prasad,24,Female,O+,73,Ahmedabad,2026-06-14,2026-09-12,Eligible
38,D0039,Samar Raja,21,Female,O+,69,Gandhinagar,2026-06-06,2026-09-04,Not Eligible
41,D0042,Ekaraj Balay,26,Female,O+,80,Ahmedabad,2026-04-22,2026-07-21,Not Eligible

In [71]:
matching = matching[
    matching["eligibility"]=="Eligible"
]

matching.head()

,donor_id,name,age,gender,blood_group,weight,city,last_donation_date,next_donation_date,eligibility
6,D0007,Jai Merchant,36,Male,O+,89,Ahmedabad,2026-05-04,2026-08-02,Eligible
30,D0031,Tejas Kapadia,32,Female,O+,92,Vadodara,2026-04-04,2026-07-03,Eligible
33,D0034,Gopal Prasad,24,Female,O+,73,Ahmedabad,2026-06-14,2026-09-12,Eligible
54,D0055,Udarsh Ramachandran,19,Male,O+,59,Surat,2026-02-14,2026-05-15,Eligible
68,D0069,Nathan Mitra,31,Male,O+,53,Gandhinagar,2026-05-13,2026-08-11,Eligible

In [72]:
matching = matching[
    matching["city"] ==
    emergency_request["city"]
]

matching.head()

,donor_id,name,age,gender,blood_group,weight,city,last_donation_date,next_donation_date,eligibility
6,D0007,Jai Merchant,36,Male,O+,89,Ahmedabad,2026-05-04,2026-08-02,Eligible
33,D0034,Gopal Prasad,24,Female,O+,73,Ahmedabad,2026-06-14,2026-09-12,Eligible
128,D0129,Jeet Sama,59,Female,O+,78,Ahmedabad,2026-02-22,2026-05-23,Eligible
228,D0229,Fariq Narula,57,Female,O+,67,Ahmedabad,2026-04-09,2026-07-08,Eligible
267,D0268,Patrick Sanghvi,46,Female,O+,62,Ahmedabad,2026-06-11,2026-09-09,Eligible

In [ ]:
Scoring Function

In [78]:
def calculate_score(row):

    score = 0

    if row["eligibility"]=="Eligible":
        score += 50

    if row["report_weight"] >= 60:
        score += 10

    if 18 <= row["age"] <= 40:
        score += 10

    score += 30

    return score

In [74]:
matching["score"] = matching.apply(
    calculate_score,
    axis=1
)

matching.head()

,donor_id,name,age,gender,blood_group,weight,city,last_donation_date,next_donation_date,eligibility,score
6,D0007,Jai Merchant,36,Male,O+,89,Ahmedabad,2026-05-04,2026-08-02,Eligible,100
33,D0034,Gopal Prasad,24,Female,O+,73,Ahmedabad,2026-06-14,2026-09-12,Eligible,100
128,D0129,Jeet Sama,59,Female,O+,78,Ahmedabad,2026-02-22,2026-05-23,Eligible,90
228,D0229,Fariq Narula,57,Female,O+,67,Ahmedabad,2026-04-09,2026-07-08,Eligible,90
267,D0268,Patrick Sanghvi,46,Female,O+,62,Ahmedabad,2026-06-11,2026-09-09,Eligible,90

In [75]:
recommended = matching.head(
    emergency_request["units_required"]
)

recommended

,donor_id,name,age,gender,blood_group,weight,city,last_donation_date,next_donation_date,eligibility,score
6,D0007,Jai Merchant,36,Male,O+,89,Ahmedabad,2026-05-04,2026-08-02,Eligible,100
33,D0034,Gopal Prasad,24,Female,O+,73,Ahmedabad,2026-06-14,2026-09-12,Eligible,100
128,D0129,Jeet Sama,59,Female,O+,78,Ahmedabad,2026-02-22,2026-05-23,Eligible,90

Recommendation Function

In [76]:
def recommend_donors(
        blood_group,
        city,
        units_required):

    donors = pd.read_sql(
        "SELECT * FROM donor_eligibility",
        engine
    )

    donors = donors[
        (donors["blood_group"]==blood_group)
        &
        (donors["city"]==city)
        &
        (donors["eligibility"]=="Eligible")
    ]

    donors["score"] = donors.apply(
        calculate_score,
        axis=1
    )

    donors = donors.sort_values(
        "score",
        ascending=False
    )

    return donors.head(
        units_required
    )

In [79]:
recommend_donors(
    "O+",
    "Ahmedabad",
    5
)

,donor_id,name,age,gender,blood_group,donor_weight,city,report_id,hemoglobin,report_weight,systolic_bp,diastolic_bp,pulse,eligibility,score
6,D0007,Jai Merchant,36,Male,O+,89,Ahmedabad,HR00007,13.2,61,115,81,71,Eligible,100
33,D0034,Gopal Prasad,24,Female,O+,73,Ahmedabad,HR00034,16.4,87,105,73,89,Eligible,100
406,D0407,Manan Sarraf,22,Male,O+,53,Ahmedabad,HR00407,16.0,73,94,65,64,Eligible,100
421,D0422,Chakrika Butala,29,Male,O+,74,Ahmedabad,HR00422,14.7,77,125,71,62,Eligible,100
771,D0772,Peter Wali,18,Female,O+,79,Ahmedabad,HR00772,17.7,67,129,68,90,Eligible,100

In [80]:
recommendation_history = pd.DataFrame(columns=[
    "request_id",
    "blood_group",
    "city",
    "recommended_donor"
])

recommendation_history.to_sql(
    "recommendation_history",
    engine,
    if_exists="replace",
    index=False
)

0

In [81]:
pd.read_sql("""
SELECT
blood_group,
COUNT(*)
AS total
FROM donor_eligibility
WHERE eligibility='Eligible'
GROUP BY blood_group
""", engine)

  blood_group  total
0          A+     72
1          O-     56
2          O+     64
3          B-     81
4          A-     76
5         AB+     71
6         AB-     71
7          B+     51

In [82]:
pd.read_sql("""
SELECT
city,
COUNT(*)
AS donors
FROM donor_eligibility
WHERE eligibility='Eligible'
GROUP BY city
""", engine)

          city  donors
0       Rajkot     109
1    Ahmedabad     119
2  Gandhinagar     104
3        Surat     101
4     Vadodara     109

Energency Alert Message

In [83]:
def emergency_message(
        donor_id,
        blood_group):

    return f"""
Emergency Blood Request

Blood Group: {blood_group}

Dear {donor_id},

A patient urgently requires blood.
Please consider donating.
"""

In [84]:
print(
    emergency_message(
        "D0012",
        "O+"
    )
)

Emergency Blood Request

Blood Group: O+

Dear D0012,

A patient urgently requires blood.
Please consider donating.